bazaar/urls.py
from django.urls import path
from .views import CreateCurrency, DetailCurrency, UpdateCurrency, DeleteCurrency, ListCurrency
from .views import CreateCategory, DetailCategory, UpdateCategory, DeleteCategory, ListCategory
from .views import CreateAd, DetailAd, UpdateAd, DeleteAd, ListAd, UpdateAdStatus, ListPendingAd, ListRejectedAd
from .views import CreateReport, DetailReport, UpdateReport, DeleteReport, ListReport
from .views import DetailProfile, UpdateProfile
from .views import CreateReview, DetailReview, UpdateReview, DeleteReview, ListReview, MyReview
from .views import Home, TermsAndConditions, AboutUs, PrivacyPolicy
from .views import UpdateUserProfile
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.sitemaps.views import sitemap
from .sitemaps import CategorySitemap, AdSitemap, StaticViewSitemap

app_name = 'bazaar'

urlpatterns = [
    path('currency/create', CreateCurrency.as_view(), name = 'currency_create'),
    path('currency/<slug:slug>/detail', DetailCurrency.as_view(), name = 'currency_detail'),
    path('currency/<slug:slug>/update', UpdateCurrency.as_view(), name = 'currency_update'),
    path('currency/<slug:slug>/delete', DeleteCurrency.as_view(), name = 'currency_delete'),
    path('currency', ListCurrency.as_view(), name = 'currency_list'),
    path('category/create', CreateCategory.as_view(), name = 'category_create'),
    path('category/<slug:slug>/detail', DetailCategory.as_view(), name = 'category_detail'),
    path('category/<slug:slug>/update', UpdateCategory.as_view(), name = 'category_update'),
    path('category/<slug:slug>/delete', DeleteCategory.as_view(), name = 'category_delete'),
    path('category', ListCategory.as_view(), name = 'category_list'),
    path('ad/create', CreateAd.as_view(), name='ad_create'),
    path('ad/<slug:slug>/detail', DetailAd.as_view(), name='ad_detail'),
    path('ad/<slug:slug>/update', UpdateAd.as_view(), name='ad_update'),
    path('ad/<slug:slug>/delete', DeleteAd.as_view(), name='ad_delete'),
    path('ad', ListAd.as_view(), name='ad_list'),
    path('ad/<slug:slug>/moderate', UpdateAdStatus.as_view(), name='ad_moderate'),
    path('ad/pending', ListPendingAd.as_view(), name='ad_pending'),
    path('ad/rejected', ListRejectedAd.as_view(), name='ad_rejected'),
    path('report/create/ad/<int:pk>', CreateReport.as_view(), name='report_create'),
    path('report/<int:pk>', DetailReport.as_view(), name='report_detail'),
    path('report/<int:pk>/update', UpdateReport.as_view(), name='report_update'),
    path('report/<int:pk>/delete', DeleteReport.as_view(), name='report_delete'),
    path('report/', ListReport.as_view(), name='report_list'),
    path('profile/detail', DetailProfile.as_view(), name='profile_detail'),
    path('profile/update', UpdateProfile.as_view(), name = 'profile_update'),
    path('review/<slug:slug>/create', CreateReview.as_view(), name='review_create'),
    path('review/<int:pk>/detail', DetailReview.as_view(), name='review_detail'),
    path('review/<int:pk>/update', UpdateReview.as_view(), name='review_update'),
    path('review/<int:pk>/delete', DeleteReview.as_view(), name='review_delete'),
    path('review/<slug:slug>', ListReview.as_view(), name='review_list'),
    path('my_reviews', MyReview.as_view(), name='my_reviews'),
    path('user/update', UpdateUserProfile.as_view(), name='profile_user_update'),
    path('password/update', PasswordChangeView.as_view(success_url = reverse_lazy('bazaar:profile_detail'), template_name = 'bazaar/profile_form.html'), name = 'profile_password_update'),
    path('', Home.as_view(), name='home'),
    path('terms-and-conditions', TermsAndConditions.as_view(), name='terms_and_conditions'),
    path('about-us', AboutUs.as_view(), name='about_us'),
    path('privacy-policy', PrivacyPolicy.as_view(), name='privacy_policy'),
    path('sitemap.xml', sitemap, {'sitemaps': { 'static':  StaticViewSitemap ,'category': CategorySitemap, 'ad': AdSitemap }}, name = 'django.contrib.sitemaps.views.sitemap')
]

note/urls.py
from django.urls import path
from note import views

app_name = "note"

urlpatterns = [
    path("create", views.CreateNote.as_view(), name = "create"),
    path("<int:pk>", views.ReadNote.as_view(), name = "read"),
    path("<int:pk>/update", views.UpdateNote.as_view(), name = "update"),
    path("<int:pk>/delete", views.DeleteNote.as_view(), name = "delete"),
    path("", views.ListNote.as_view(), name="list")
]

scull_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# for deploy uploaded files. Only for development
# environments
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),    
    path("note/", include("note.urls")),
    path("accounts/", include("accounts.urls")),
    path('bazaar/', include('bazaar.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('feedback/', include('feedback.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('image2text/', include('image2text.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Remember, only for debug mode! This code does not work on production environment..

bazaar/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, TemplateView
from .models import Currency, Category, Ad, Report, Profile, Review
from .forms import CurrencyForm, CategoryForm, AdForm, AdStatusForm, ReportForm, ProfileForm, ReviewForm, AdvancedSearchForm
from accounts.forms import UserAdminForm, UserForm
from accounts.views import UpdateUser
from django.urls import reverse_lazy
from django.db.models import Q, F
from .helpers import normalize_ad_pictures, get_simple_search_form, get_profile_stats
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models import Sum, FloatField, ExpressionWrapper
from django.db import IntegrityError
from django.forms import ValidationError

# Create your views here.

class CreateCurrency(UserPassesTestMixin, CreateView):
    model = Currency
    form_class = CurrencyForm
    success_url = reverse_lazy('bazaar:currency_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)        
        context = get_simple_search_form(context)
        return context

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.add_currency')

class DetailCurrency(UserPassesTestMixin, DetailView):
    model = Currency

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.view_currency')

class UpdateCurrency(UserPassesTestMixin, UpdateView):
    model = Currency
    form_class = CurrencyForm
    success_url = reverse_lazy('bazaar:currency_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.change_currency')

class DeleteCurrency(UserPassesTestMixin, DeleteView):
    model = Currency
    success_url = reverse_lazy('bazaar:currency_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.delete_currency')
    

class ListCurrency(UserPassesTestMixin, ListView):
    model = Currency

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.view_currency')        
    

class CreateCategory(UserPassesTestMixin, CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('bazaar:category_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.add_category')
    

class DetailCategory(UserPassesTestMixin, DetailView):
    model = Category

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.view_category')
    

class UpdateCategory(UserPassesTestMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('bazaar:category_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.change_category')
    

class DeleteCategory(UserPassesTestMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('bazaar:category_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.delete_category')
    

class ListCategory(UserPassesTestMixin, ListView):
    model = Category

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.view_category')
    

class CreateAd(LoginRequiredMixin, CreateView):
    model = Ad
    form_class = AdForm
    success_url = reverse_lazy('bazaar:ad_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)        
        context = get_simple_search_form(context)
        return context

    def post(self, request: HttpRequest, *args: str, **kwargs) -> HttpResponse:        
        self.request = normalize_ad_pictures(request, (748, 420)) # TODO: You need to use self.request.POST = self.request.POST.copy()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.owner = self.request.user
        self.object.save()
        
        return HttpResponseRedirect(self.get_success_url())
    

class DetailAd(DetailView):
    model = Ad

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        reviews = Review.objects.filter(reviewed = self.get_object().owner.profile)

        context = get_profile_stats(self.get_object().owner.profile, context)
    
        return context
    

class UpdateAd(UserPassesTestMixin, UpdateView):
    model = Ad
    form_class = AdForm
    success_url = reverse_lazy('bazaar:ad_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.request = normalize_ad_pictures(request, (748, 420)) # TODO: You need to use self.request.POST = self.request.POST.copy().
        return super().post(request, *args, **kwargs)

    
    def form_valid(self, form):
        
        if not (self.request.user.is_superuser or self.request.user.groups.filter(Q(name = 'Bazaar Superuser') | Q(name = 'Bazaar Moderator')).exists()):
            ad = form.save(commit = False)
            ad.status = 0 # Pending status..
            ad.save()
        else:
            form.save(commit = True)

        return HttpResponseRedirect(self.get_success_url())
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.change_ad') or self.get_object().owner == self.request.user


class DeleteAd(UserPassesTestMixin, DeleteView):
    model = Ad
    success_url = reverse_lazy('bazaar:ad_list')

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context = get_simple_search_form(context)
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('bazaar.delete_ad') or self.get_object().owner == self.request.user
    

class ListAd(ListView):
    model = Ad

    def get_queryset(self):

        if 'my_ads' not in self.request.GET.keys():
            queryset = Ad.objects.filter(status = 2)
        else:
            queryset = Ad.objects.all()

        keyword_queryset = self.request.GET.get('query', '')
        price_start = self.request.GET.get('price_start', '')
        price_end = self.request.GET.get('price_end', '')
        currencies = self.request.GET.getlist('currencies', [])
        date_start = self.request.GET.get('date_start', '')
        date_end = self.request.GET.get('date_end', '')
        category = self.request.GET.get('category', '')
        my_ads = self.request.GET.get('my_ads', '')

        if keyword_queryset:
            queryset = queryset.filter(Q(title__icontains=keyword_queryset) | Q(description__icontains=keyword_queryset))
        
        if price_start:
            queryset = queryset.filter(Q(price__gte=price_start))

        if price_end:
            queryset = queryset.filter(Q(price__lte=price_end))

        if currencies:
            currencies = self.request.GET.getlist('currencies')
            currency_query = Q(currency__slug=currencies[0])

            for currency in currencies[1:]:
                currency_query = Q(currency_query | Q(alternative_currencies__slug=currency))

            queryset = queryset.filter(currency_query).distinct()

        if date_start:
            queryset = queryset.filter(Q(date__gte=date_start))

        if date_end:
            queryset = queryset.filter(Q(date__lte=date_end))
        
        if category:

bazaar/templates/bazaar/about_us.html
{% extends "bazaar/base.html" %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:about_us" %}{% endblock %}
{% block page_description %}Nuestra mision es facilitar el intercambio entre personas...{% endblock %}

{% block title %}Quienes somos{% endblock %}

{% block main %}
<h1>Quiénes Somos</h1>

<p>
    Bazaar, conectando personas para facilitar el intercambio seguro y fácil 
    de bienes, servicios y criptomonedas.
</p>

<h2>Nuestra Misión</h2>

<p>
    En Bazaar, nuestra misión es facilitar el intercambio entre personas de 
    una manera segura y accesible. Queremos crear un espacio donde los 
    usuarios puedan comprar, vender y conectar sin barreras, utilizando 
    criptomonedas o divisas tradicionales.
</p>

<h2>¿Cómo Funciona?</h2>

<p>
    Nuestra plataforma conecta a compradores y vendedores, permitiendo 
    que las transacciones se realicen entre pares. No intermediamos en 
    las compras, pero proporcionamos las herramientas necesarias para 
    facilitar el intercambio de bienes y servicios de manera segura. 
    Con Bazaar, puedes ponerte en contacto con personas para realizar 
    transacciones en diversas divisas, incluyendo criptomonedas. 
    Para ello los usuarios interesados en comprar o vender, publican 
    anuncios. Estos anuncios serán moderados antes de ser aprobados, 
    para garantizar que solo se muestren ofertas que cumplan los 
    términos y condiciones de la plataforma. Una vez aprobados, los 
    anuncios estarán visibles durante un mes.
</p>

<h2>Valores y Compromiso</h2>

<p>
    Nos importa tu seguridad y confianza. En Bazaar, nos comprometemos 
    a proporcionar un espacio donde las transacciones se realicen de 
    manera transparente, con sistemas de seguridad de última generación 
    y con un equipo siempre dispuesto a ayudarte.
</p>

<h2>¿Por qué Elegirnos?</h2>
<ul>
    <li>
        Seguridad: Nos comprometemos a proteger tus datos mediante diversas 
        medidas de seguridad y trabajamos paa implementar tecnologías de 
        cifrado para mejorar la privacidad de nuestros usuarios.
    </li>
    <li>
        Facilidad de uso: La plataforma es simple y fácil de navegar.
    </li>
    <li>
        Variedad de opciones: Compra, venta e intercambio de divisas y 
        criptomonedas.
    </li>
    <li>
        Soporte: Estamos aquí para asistirte en cada paso del proceso.
    </li>
</ul>

<h2>El Equipo Detrás</h2>

<p>
    Soy Ariel Hernández Scull, el creador de Bazaar. Como desarrollador 
    y emprendedor, decidí crear una plataforma que facilite la 
    compra-venta entre personas, con un enfoque en seguridad y 
    facilidad de uso. ¡Gracias por confiar en nosotros!
</p>

<h2>Contacto</h2>

<p>TODO: Put a contact form here</p>

<p>
    Unete a Bazaar y comienza a comerciar. Registrate ahora y explora 
    las categorías de anuncios!
</p>
{% endblock %}

bazaar/templates/bazaar/ad_form.html
{% extends "bazaar/base.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% if object.pk %}{% url "bazaar:ad_update" slug=object.slug%}{% else %}{% url "bazaar:ad_create" %}{% endif %}{% endblock %}
{% block page_description %}{% include "action_label.html" %} {% translate "an advertesiment" %}{% endblock %}

{% block title_prefix %}{% include "action_label.html" %} {% translate "an advertesiment" %}{% endblock %}

{% block main %}
    <h1>{% include "action_label.html" %} {% translate "an advertesiment" %}</h1>
    <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">{% include "action_label.html" %} {% translate "Ad" %}</button>
    </form>
{% endblock %}

bazaar/templates/bazaar/ad_pending_list.html
{% extends "bazaar/ad_list.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:ad_pending" %}{% if request.META.QUERY_STRING %}/?{{ request.META.QUERY_STRING }}{% endif %}{% endblock %}
{% block page_description %}{{ category_description|default:_("Search results") }}{% endblock %}

{% block title_prefix %}{% translate "Pending ads" %}{% endblock %}

{% block current_page %}
    {% translate "Pending ads" %}
{% endblock  %}

{% block no_ads_message %}
    {% translate "There are not pending ads." %}
{% endblock %}

bazaar/templates/bazaar/ad_rejected_list.html
{% extends "bazaar/ad_list.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:ad_rejected" %}{% endblock %}
{% block page_description %}{% translate "Rejected ads" %}{% endblock %}

{% block title_prefix %}{% translate "Rejected ads" %}{% endblock %}

{% block current_page %}
    {% translate "Rejected ads" %}
{% endblock  %}

{% block no_ads_message %}
    {% translate "There are not rejected ads." %}
{% endblock %}

bazaar/templates/bazaar/category_detail.html
{% extends "bazaar/base.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:category_detail" slug=object.slug%}{% endblock %}
{% block page_description %}{{ object.description }}{% endblock %}

{% block title_prefix %}{{ object.name }}{% endblock %}

{% block main %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.description }}</p>
    <a class="btn btn-primary" href="{% url "bazaar:category_update" slug=object.slug %}">{% translate "Update" %}</a>
    <a class="btn btn-danger" href="{% url "bazaar:category_delete" slug=object.slug %}">{% translate "Delete" %}</a>
{% endblock %}

bazaar/templates/bazaar/currency_confirm_delete.html
{% extends "bazaar/base.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:currency_delete" slug=object.slug %}{% endblock %}
{% block page_description %}{% translate "Confirm currency delete" %}{% endblock %}

{% block title_prefix %}{% translate "Confirm delete currency" %}{% endblock %}

{% block main %}
    <h1>{% translate "Are you sure?" %}</h1>
    <p>{% translate "You are about to delete a currency and all objects related to them. This action can't be undone. Please confirm:" %}</p>
    <a class="btn btn-primary" href="{% url "bazaar:currency_list" %}">{% translate "No" %}</a>
    <form action="" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="{% translate "Yes" %}">
    </form>
{% endblock %}

bazaar/templates/bazaar/currency_form.html
{% extends "bazaar/base.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% if object.pk %}{% url "bazaar:currency_update" slug=object.slug%}{% else %}{% url "bazaar:currency_create" %}{% endif %}{% endblock %}
{% block page_description %}{% if object.pk %}{{ object.name }} {% else %}{% translate "Create new currency" %}{% endif %}{% endblock %}

{% block title_prefix %}{% include "action_label.html" %} {% translate "a currency" %}{% endblock  %}

{% block main %}
    <h1>{% include "action_label.html" %} {% translate "a currency" %}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-4">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}        
        <div class="mx-auto p-2" style="width: 200px">
            <button type="submit" class="btn btn-success">{% include "action_label.html" %} {% translate "Currency" %}</button>
        </div>
    </form>
{% endblock %}

bazaar/templates/bazaar/header.html
{% extends "header.html" %}

{% load i18n %}

{% block offcanvas_header %}
    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Bazaar</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="{% translate "Close" %}"></button>
{% endblock %}

{% block offcanvas_body %}
    <form class="d-flex" role="search" action="{% url "bazaar:ad_list" %}" method="get">
        {{ simple_search_form.query }}
        <button class="btn btn-outline-success">{% translate "Search" %}</button>
    </form>
    <ul class="navbar-nav">
        {% include "theme_button.html" %}
        {% with user_permissions=user.get_all_permissions %}
            {% if user.is_superuser or 'bazaar.view_category' in user_permissions %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "bazaar:category_list" %}">{% translate "Categories" %}</a>
                </li>                
            {% endif %}
            {% if user.is_superuser or 'bazaar.view_currency' in user_permissions%}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "bazaar:currency_list" %}">{% translate "Currencies" %}</a>
                </li>
            {% endif %}
            {% if user.is_superuser or 'bazaar.view_report' in user_permissions %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "bazaar:report_list" %}">{% translate "Reports" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "bazaar:ad_pending" %}">{% translate "Pending Ads" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "bazaar:ad_rejected" %}">{% translate "Rejected Ads" %}</a>
                </li>
            {% endif %}
            {% if user.is_superuser or 'auth.view_user' in user_permissions %}
                <li class="nav-item">                    
                    <a class="nav-link" target="_blank" href="{% url "user_list" %}">{% translate "Users" %}</a>
                </li>
            {% endif %}
        {% endwith %}

        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "bazaar:ad_create" %}">{% translate "New Ad" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "bazaar:ad_list" %}?my_ads=true">{% translate "My Ads" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "bazaar:profile_detail" %}">{% translate "Profile" %}</a>
            </li>
            <li class="nav-item">
                <form action="{% url "logout" %}?next={{ request.path }}" method="post">
                    {% csrf_token %}
                    <input class="nav-link" type="submit" value="{% translate "Logout" %}">
                </form>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "login" %}?next={{ request.path }}">{% translate "Login" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "register" %}">{% translate "Register" %}</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

bazaar/templates/bazaar/profile_form.html
{% extends "bazaar/base.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:profile_update" %}{% endblock %}
{% block page_description %}{% translate "User Profile" %}{% endblock %}

{% block title_prefix %}{% translate "User Profile" %}{% endblock  %}

{% block main %}
    <h1>{% translate "User Profile" %}</h1>

    <div class="p-3 m-3 bg-body-tertiary">
        <form action="{% url "bazaar:profile_user_update" %}" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input class="btn btn-primary" type="submit" value="{% include "action_label.html" %} basic info">
        </form>
    </div>
    
    <div class="p-3 m-3 bg-body-tertiary">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="{% include "action_label.html" %} aditional info">
        </form>
    </div>
    
    <div class="p-3 m-3 bg-body-tertiary">
        <form action="{% url "bazaar:profile_password_update" %}" method="post">
            {% csrf_token %}
            {{ password_form.as_p }}
            <input class="btn btn-primary" type="submit" value="{% include "action_label.html" %} password">
        </form>
    </div>
    
{% endblock %}

bazaar/templates/bazaar/report_confirm_delete.html
{% extends "bazaar/base.html" %}

{% load i18n %}

{% block canonical_href %}{{ request.scheme }}://{{ request.get_host }}{% url "bazaar:report_delete" pk=object.pk %}{% endblock %}
{% block page_description %}{% translate "Confirm delete report" %}{% endblock %}

{% block title_prefix %}{% translate "Confirm delete report" %}{% endblock %}

{% block main %}
    <h1>{% translate "Are you sure?" %}</h1>
    <p>{% translate "You are about to delete a report. This action can't be undone. Please confirm:" %}</p>
    <a href="{% url "bazaar:report_list" %}">{% translate "No" %}</a>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="{% translate "Yes" %}">
    </form>
{% endblock %}