note/urls.py
from django.urls import path
from note import views

app_name = "note"

urlpatterns = [
    path("create", views.CreateNote.as_view(), name = "create"),
    path("<int:pk>", views.ReadNote.as_view(), name = "read"),
    path("<int:pk>/update", views.UpdateNote.as_view(), name = "update"),
    path("<int:pk>/delete", views.DeleteNote.as_view(), name = "delete"),
    path("", views.ListNote.as_view(), name="list")
]

scull_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# for deploy uploaded files. Only for development
# environments
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),    
    path("note/", include("note.urls")),
    path("accounts/", include("accounts.urls")),
    path('bazaar/', include('bazaar.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('feedback/', include('feedback.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('image2text/', include('image2text.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Remember, only for debug mode! This code does not work on production environment..

note/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Note(models.Model):
    title = models.CharField("Title", max_length=50)
    body = models.TextField("Body")
    tags = models.CharField("Tags", max_length=50)
    date = models.DateField("Date", auto_now=True)
    time = models.TimeField("Time", auto_now=True)
    owner = models.ForeignKey(User, verbose_name="Owner", on_delete=models.CASCADE)

    def __str__(self):
        return self.title[0:9]

note/forms.py
from typing import Any
from django.forms import ModelForm, TextInput, Textarea
from note.models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body', 'tags']
        widgets = {            
            'title': TextInput(attrs={'class': 'form-control'}),
            'tags': TextInput(attrs={'class': 'form-control'}),
            'body': Textarea(attrs={'class': 'form-control'}),
        }

note/views.py
from typing import Any, Optional
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from note.models import Note
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from note.forms import NoteForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from .helpers import is_user_the_owner, set_owner

# Create your views here.

class CreateNote(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy("note:list")

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        request = set_owner(request)
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.owner = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    
class ReadNote(UserPassesTestMixin, DetailView):
    model = Note
    
    def test_func(self) -> bool | None:
        return is_user_the_owner(self)


class UpdateNote(UserPassesTestMixin, UpdateView):
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy("note:list")
    
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        request = set_owner(request)
        return super().post(request, *args, **kwargs)
    
    def test_func(self) -> bool | None:
        return is_user_the_owner(self)


class DeleteNote(UserPassesTestMixin, DeleteView):
    model = Note
    success_url = reverse_lazy("note:list")

    def test_func(self) -> bool | None:
        return is_user_the_owner(self)

class ListNote(LoginRequiredMixin, ListView):
    model = Note

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.GET.__contains__("search"):
            search_pattern = self.request.GET["search"]
            return Note.objects.filter(owner_id=self.request.user.id).filter(Q(title__contains=search_pattern) | Q(body__contains=search_pattern) | Q(tags__contains=search_pattern))
                  
        return Note.objects.filter(owner_id=self.request.user.id)

note/templates/note/base.html
{% extends "base.html" %}

{% block header %}
    {% url "note:list" as note_list %}
    {% include "note/header.html" with url=note_list icon='bi-journal' title='Note' %}
{% endblock %}

note/templates/note/header.html
{% extends "header.html" %}

{% block offcanvas_header %}
    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Note</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
{% endblock %}

{% block offcanvas_body %}
    <div class="d-flex">
        <form action="" method="GET">
            <input type="text" name="search" id="">
            <input type="submit" value="Search" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

note/templates/note/list_toolbar.html
{% extends "toolbar.html" %}

{% block left_buttons %}
    <div class="nav-item">
        <a class="btn btn-primary" href="{% url 'note:create' %}">Create</a>
    </div>
{% endblock %}

{% block right_buttons %}    
    <div class="nav-item">
        <div class="d-flex">
            <span class="nav-link">Action: </span>
            <select class="form-select" name="action" id="">
                <option value="0" default>---</option>
                <option value="1">Delete</option>
            </select>
            <input class="btn btn-primary ms-2" type="submit" value="Go">
        </div>
    </div>
{% endblock %}

note/templates/note/note_confirm_delete.html
{% extends 'note/base.html' %}

{% block title %}Confirm delete{% endblock title %}

{% block main %}
    <h1>Are you sure?</h1>
    <p>Are you sure to delete this note? This action can be undone..</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Delete note">
    </form>
{% endblock %}

note/templates/note/note_detail.html
{% extends 'note/base.html' %}

{% block title %}Note: {{ object.title }}{% endblock title %}

{% block main %}
    <h1>{{ object.title }}</h1>
    <p>{{ object.body }}</p>
    <p>Tags: {{ object.tags }}</p>
    <a href="{% url 'note:update' object.pk %}" class="btn btn-secondary">Update</a>
    <a href="{% url 'note:delete' object.pk %}" class="btn btn-danger">Delete</a>
{% endblock %}

note/templates/note/note_form.html
{% extends 'note/base.html' %}

{% block title %}Create a note{% endblock title %}

{% block main %}
    <h1>Create a note</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% include "action_label.html" %}" class="btn btn-primary">
    </form>
    
{% endblock %}

note/templates/note/note_list.html
{% extends 'note/base.html' %}

{% block title %}Notes{% endblock %}

{% block main %}

    <form action="{% url 'note:list' %}" method="post">
        {% csrf_token %}
        {% include "note/list_toolbar.html" %}
        
        <table class="table table-hover">
            <tbody>
                {% for note in object_list %}
                    <tr>                    
                        <td>
                            <input type="checkbox" name="selectedNote" value="{{ note.id }}">
                        </td>
                        <td>                        
                            <a href="{% url 'note:read' note.id %}">
                                {% if note.title|length > 16 %}
                                    {{ note.title|slice:16 }} ...
                                {% else %}
                                    {{ note.title }}
                                {% endif %}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'note:read' note.id %}">
                                {% if note.body|length > 16 %}
                                    {{ note.body|slice:16 }} ...
                                {% else %}
                                    {{ note.body }}
                                {% endif %}
                            </a>
                        </td>
                        <td>
                            {{ note.date }}
                        </td>
                        <td>{{ note.time }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}