bazaar/urls.py
from django.urls import path
from .views import CreateCurrency, DetailCurrency, UpdateCurrency, DeleteCurrency, ListCurrency
from .views import CreateCategory, DetailCategory, UpdateCategory, DeleteCategory, ListCategory
from .views import CreateAd, DetailAd, UpdateAd, DeleteAd, ListAd, UpdateAdStatus, ListPendingAd, ListRejectedAd
from .views import CreateReport, DetailReport, UpdateReport, DeleteReport, ListReport
from .views import DetailProfile, UpdateProfile
from .views import CreateReview, DetailReview, UpdateReview, DeleteReview, ListReview, MyReview
from .views import Home, TermsAndConditions, AboutUs, PrivacyPolicy
from .views import UpdateUserProfile
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.sitemaps.views import sitemap
from .sitemaps import CategorySitemap, AdSitemap, StaticViewSitemap

app_name = 'bazaar'

urlpatterns = [
    path('currency/create', CreateCurrency.as_view(), name = 'currency_create'),
    path('currency/<slug:slug>/detail', DetailCurrency.as_view(), name = 'currency_detail'),
    path('currency/<slug:slug>/update', UpdateCurrency.as_view(), name = 'currency_update'),
    path('currency/<slug:slug>/delete', DeleteCurrency.as_view(), name = 'currency_delete'),
    path('currency', ListCurrency.as_view(), name = 'currency_list'),
    path('category/create', CreateCategory.as_view(), name = 'category_create'),
    path('category/<slug:slug>/detail', DetailCategory.as_view(), name = 'category_detail'),
    path('category/<slug:slug>/update', UpdateCategory.as_view(), name = 'category_update'),
    path('category/<slug:slug>/delete', DeleteCategory.as_view(), name = 'category_delete'),
    path('category', ListCategory.as_view(), name = 'category_list'),
    path('ad/create', CreateAd.as_view(), name='ad_create'),
    path('ad/<slug:slug>/detail', DetailAd.as_view(), name='ad_detail'),
    path('ad/<slug:slug>/update', UpdateAd.as_view(), name='ad_update'),
    path('ad/<slug:slug>/delete', DeleteAd.as_view(), name='ad_delete'),
    path('ad', ListAd.as_view(), name='ad_list'),
    path('ad/<slug:slug>/moderate', UpdateAdStatus.as_view(), name='ad_moderate'),
    path('ad/pending', ListPendingAd.as_view(), name='ad_pending'),
    path('ad/rejected', ListRejectedAd.as_view(), name='ad_rejected'),
    path('report/create/ad/<int:pk>', CreateReport.as_view(), name='report_create'),
    path('report/<int:pk>', DetailReport.as_view(), name='report_detail'),
    path('report/<int:pk>/update', UpdateReport.as_view(), name='report_update'),
    path('report/<int:pk>/delete', DeleteReport.as_view(), name='report_delete'),
    path('report/', ListReport.as_view(), name='report_list'),
    path('profile/detail', DetailProfile.as_view(), name='profile_detail'),
    path('profile/update', UpdateProfile.as_view(), name = 'profile_update'),
    path('review/<slug:slug>/create', CreateReview.as_view(), name='review_create'),
    path('review/<int:pk>/detail', DetailReview.as_view(), name='review_detail'),
    path('review/<int:pk>/update', UpdateReview.as_view(), name='review_update'),
    path('review/<int:pk>/delete', DeleteReview.as_view(), name='review_delete'),
    path('review/<slug:slug>', ListReview.as_view(), name='review_list'),
    path('my_reviews', MyReview.as_view(), name='my_reviews'),
    path('user/update', UpdateUserProfile.as_view(), name='profile_user_update'),
    path('password/update', PasswordChangeView.as_view(success_url = reverse_lazy('bazaar:profile_detail'), template_name = 'bazaar/profile_form.html'), name = 'profile_password_update'),
    path('', Home.as_view(), name='home'),
    path('terms-and-conditions', TermsAndConditions.as_view(), name='terms_and_conditions'),
    path('about-us', AboutUs.as_view(), name='about_us'),
    path('privacy-policy', PrivacyPolicy.as_view(), name='privacy_policy'),
    path('sitemap.xml', sitemap, {'sitemaps': { 'static':  StaticViewSitemap ,'category': CategorySitemap, 'ad': AdSitemap }}, name = 'django.contrib.sitemaps.views.sitemap')
]

feedback/urls.py
from django.urls import path
from .views import CreateSurvey, DetailSurvey, UpdateSurvey, DeleteSurvey, ListSurvey, SubmitSurvey
from .views import CreateQuestion, DetailQuestion, UpdateQuestion, DeleteQuestion, ListQuestion
from .views import CreateAnswer, DetailAnswer, UpdateAnswer, DeleteAnswer, ListAnswer
from .views import FaqView

app_name = 'feedback'

urlpatterns = [
    path('survey/create', CreateSurvey.as_view(), name = 'survey_create'),
    path('survey/<int:pk>/detail', DetailSurvey.as_view(), name = 'survey_detail'),
    path('survey/<int:pk>/update', UpdateSurvey.as_view(), name = 'survey_update'),
    path('survey/<int:pk>/delete', DeleteSurvey.as_view(), name = 'survey_delete'),
    path('', ListSurvey.as_view(), name = 'survey_list'),
    path('survey/<int:pk>/submit', SubmitSurvey.as_view(), name='survey_submit'),
    path('question/create', CreateQuestion.as_view(), name = 'question_create'),
    path('question/<int:pk>/detail', DetailQuestion.as_view(), name = 'question_detail'),
    path('question/<int:pk>/update', UpdateQuestion.as_view(), name = 'question_update'),
    path('question/<int:pk>/delete', DeleteQuestion.as_view(), name = 'question_delete'),
    path('question', ListQuestion.as_view(), name = 'question_list'),
    path('answer/create', CreateAnswer.as_view(), name = 'answer_create'),
    path('answer/<int:pk>/detail', DetailAnswer.as_view(), name = 'answer_detail'),
    path('answer/<int:pk>/update', UpdateAnswer.as_view(), name = 'answer_update'),
    path('answer/<int:pk>/delete', DeleteAnswer.as_view(), name = 'answer_delete'),
    path('answer', ListAnswer.as_view(), name = 'answer_list'),
    path('faq', FaqView.as_view(), name = 'faq')
]

image2text/urls.py
from django.urls import path
from .views import CreateRecognition, TextDetail, FaqView

app_name = 'image2text'

urlpatterns = [
    path('', CreateRecognition.as_view(), name = 'recognition_create'),
    path('text/detail', TextDetail.as_view(), name = 'text_detail'),
    path('faq', FaqView.as_view(), name = 'faq')
]

note/urls.py
from django.urls import path
from note import views

app_name = "note"

urlpatterns = [
    path("create", views.CreateNote.as_view(), name = "create"),
    path("<int:pk>", views.ReadNote.as_view(), name = "read"),
    path("<int:pk>/update", views.UpdateNote.as_view(), name = "update"),
    path("<int:pk>/delete", views.DeleteNote.as_view(), name = "delete"),
    path("", views.ListNote.as_view(), name="list")
]

restaurant/urls.py
from django.urls import path, include
from .views import CreateReview, DetailReview, UpdateReview, DeleteReview, ListReview
from .views import Home
from .views import ReviewViewSet, AnswerViewSet, QuestionViewSet, DataViewSet
from rest_framework import routers

app_name = 'restaurant'

router = routers.DefaultRouter()
router.register(r'review', ReviewViewSet)
router.register(r'answer', AnswerViewSet)
router.register(r'question', QuestionViewSet)
router.register(r'data', DataViewSet)

urlpatterns = [
    path('', Home.as_view(), name='home'), # Keep this endpoint (static)
    path('review/create', CreateReview.as_view(), name='review_create'),
    path('review/<int:pk>', DetailReview.as_view(), name='review_detail'),
    path('review/<int:pk>/update', UpdateReview.as_view(), name='review_update'),
    path('review/<int:pk>/delete', DeleteReview.as_view(), name='review_delete'),
    path('review', ListReview.as_view(), name='review_list'),
    path('api/', include(router.urls)), # Keep this endpoint (dynamic)
]

scull_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# for deploy uploaded files. Only for development
# environments
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),    
    path("note/", include("note.urls")),
    path("accounts/", include("accounts.urls")),
    path('bazaar/', include('bazaar.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('feedback/', include('feedback.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('image2text/', include('image2text.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Remember, only for debug mode! This code does not work on production environment..

templates/action_label.html
{% load i18n %}

{% if object.pk %}{% translate "Update" %}{% else %}{% translate "Create" %}{% endif %}

templates/authenticated.html
{% extends "base.html" %}

{% block navbar %}
<!--
<div class="navbar navbar-expand-sm bg-light">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">Portfolio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'read_user' user.id %}">Your account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
-->
{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="es" data-bs-theme='{{ request.COOKIES.theme }}'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap-5.3.2-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons-1.11.3/font/bootstrap-icons.min.css' %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="shortcut icon" href="{% block page_icon %}{% static "favicon.ico" %}{% endblock %}" type="image/x-icon">
    <link rel="canonical" href="{% block canonical_href %}{{ request.get_host }}{% endblock %}" />
    <meta name='description' content='Scull Suite, aplicaciones para hacerte la vida mas fácil.'></meta>
    <title>{% block title %}{% endblock %}</title>
    <!--To monetize my site-->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8728947711978649"
     crossorigin="anonymous"></script>
     {% block rich_snippet %}{% endblock %}
</head>
<body>
    <div class="container-fluid bg-secondary-subtle">
        {% block header %}{% endblock %}
        {% block nav %}{% endblock %}
        {% block main %}{% endblock %}
        {% block footer %}{% endblock %}
    </div>
    <script src="{% static 'bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script>
        const htmlTag = document.querySelector('html');
        const themeButton = document.getElementById('theme-button');
        const themeIcon = document.getElementById('theme-icon');
        const themeText = document.getElementById('theme-text');

        function getCookieValue(cookies, key) {
            /**
                Get the value of a cookie.
            */

            return cookies.split('; ').find(row => row.startsWith(key)).split('=')[1];
        }

        function changeUI(theme) {
            /**
                Change the User Interface of the button related with the theme.
            */

            if (theme === 'light') {
                themeIcon.className = 'bi bi-sun-fill';
                themeText.textContent = '{% translate "Light" %}';
            } else {
                themeIcon.className = 'bi bi-moon-fill';
                themeText.textContent = '{% translate "Dark" %}';
            }
        }

        function changeTheme() {
            /**
                Change the theme of the site.
            */

            
            if (getCookieValue(document.cookie, 'theme') === 'light') {
                document.cookie = 'theme=dark; path=/';
                changeUI('dark');
                htmlTag.setAttribute('data-bs-theme', 'dark');
            } else {
                document.cookie = 'theme=light; path=/';
                changeUI('light');
                htmlTag.setAttribute('data-bs-theme', 'light');
            }
        }
        window.onload = () => {
            if (!document.cookie.includes('theme')) {
                document.cookie = 'theme=light; path=/';
            }
        }
        themeButton.addEventListener('click', changeTheme);
    </script>
    {% block body_bottom %}{% endblock  %}
</body>
</html>

templates/header.html
{% extends "navbar.html" %}

{% block navbar_content %}
    
    <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <a class="navbar-brand" href="{{ url }}"><i class="bi bi-{{ icon }}"></i> {{ title }}</a>

    <div>
        <!-- Useful to center navbar logo on small screens. -->
    </div>

    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
            {% block offcanvas_header %}{% endblock %}
        </div>
        
        <div class="offcanvas-body justify-content-end">
            {% block offcanvas_body %}{% endblock %}
        </div>
    </div>
    
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block title %}Scull Suite, {% translate "Applications to make your life easier" %}{% endblock %}

{% block header %}
    {% include "home_header.html" with icon="briefcase" title="Scull Suite" %}
{% endblock %}

{% block main %}
    <main class="container-fluid">
        
        <div id="start" class="text-light d-flex flex-column min-vh-100 justify-content-center align-items-center" style="background-image:url('{% static 'img/web_developer1.jpg' %}')">
            
            <h1 class="bg-dark">Scull Suite</h1>
            <h2 class="bg-dark">{% translate "Applications to make your life easier" %}</h2>
            <a class="btn btn-primary" href="#applications">{% translate "Show applications" %}</a>
        </div>

        <section id="applications" class="d-flex flex-column min-vh-100 text-center">
            
            <h2>{% translate "Applications" %}</h2>

            <div class="row">
                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/image2text_app.jpg' %}" alt="{% translate "Image2Text application" %}">
                        
                        <div class="card-body">
                            <p class="card-text">
                                Extrae el texto presente en una imagen en cuestión de segundos. 
                                Sin registro, sin instalaciones. Fácil, rapido y privado.
                            </p>
                            <a href="{% url "image2text:recognition_create" %}" target="_blank">Image2Text</a>
                        </div>
                    </div>
                </div> 

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/transcribe_app.jpg' %}" alt="{% translate "Transcribe application" %}">
                        
                        <div class="card-body">
                            <p class="card-text">
                                Tienes notas de voz, una grabacion de tu profesor hablando 
                                o una entrevista grabada? Pues convierte el audio a texto 
                                con esta aplicacion. Fácil, rápido y privado.
                            </p>
                            <a href="{% url "transcribe:transcription_create" %}" target="_blank">Transcribe</a>
                        </div>
                    </div>
                </div>                
            </div>

            <div class="row">

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/feedback_app.jpg' %}" alt="{% translate "Feedback application" %}">
                        
                        <div class="card-body">
                            <p class="card-text">
                                Una aplicacion que te permite realizar encuestas y obtener estadisticas utiles para tu negocio o investigacion.
                            </p>
                            <a href="{% url "feedback:survey_list" %}" target="_blank">Feedback</a>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/restaurant_app.jpg' %}" alt="{% translate "Restaurant application" %}">
                        
                        <div class="card-body">
                            <p class="card-text">
                                Esta aplicación permite automatizar, mediante un asistente virtual,
                                la atencion de preguntas frecuentes por parte de los clientes de tu 
                                restaurante. En breve se añadiran mas funcionalidades. Mantente alerta!
                            </p>
                            <a href="{% url "restaurant:home" %}" target="_blank">Restaurant</a>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/note_project.png' %}" alt="Note project using Django and other tools">
                        
                        <div class="card-body">
                            <p class="card-text">
                                ¿Tienes notas en papel o digitales por todas partes? Es una pesadilla gestionarlas
                                y acaba con tu productividad.. Pues con esta aplicación podras gestionar tus notas, 
                                desde cualquier dispositivo y lugar. Pruébala!
                            </p>
        
                            <a href="{% url "note:list" %}" target="_blank">Note</a>
                        </div>
                        
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/bazaar_project.jpg' %}" alt="Bazaar project using Django and other tools">
                        
                        <div class="card-body">
                            <p class="card-text">
                                Esta aplicación te permite comprar, vender y alquilar bienes y servicios, utilizando
                                dinero fiudiciario y criptomonedas. Busca y encuentra lo que necesitas aquí!
                            </p>        
                            <a href="{% url "bazaar:home" %}" target="_blank">Bazaar</a>
                        </div>
                    </div>
                </div>
            </div>
            
        </section>

        <section class="text-center" id="contact_me">
            
            <h2>{% translate "Contact" %}</h2>

            <img class="img-fluid" src="{% static 'img/telegram.svg' %}" alt="Telegram">
            <a href="http://t.me/ascull" target="_blank">Telegram</a>
            
            
            <img class="img-fluid" src="{% static 'img/linkedin.svg' %}" alt="LinkedIn">
            <a href="http://www.linkedin.com/in/ariel-scull-b4a598183" target="_blank">LinkedIn</a>

        </section>

    </main>
{% endblock %}

templates/home_backup.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Scull Suite{% endblock %}

{% block header %}
    {% include "home_header.html" with icon="briefcase" title="Portfolio" %}
{% endblock %}

{% block main %}   

    <main class="container-fluid">
        
        <div id="start" class="text-light d-flex flex-column min-vh-100 justify-content-center align-items-center" style="background-image:url('{% static 'img/web_developer1.jpg' %}')">
            
            <h1 class="bg-dark">Ariel Hernandez Scull</h1>
            <h2 class="bg-dark">Web / ML Developer</h2>
            <a class="btn btn-primary" href="#portfolio">Show portfolio</a>
        </div>

        <section id="portfolio" class="d-flex flex-column min-vh-100 text-center">
            
            <h2>Portfolio</h2>

            <div class="row">

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/restaurant_app.jpg' %}" alt="Restaurant project using Django and other tools">
                        
                        <div class="card-body">
                                
                            <div>                                
                                <img style="width:5vw" src="{% static 'img/python.svg' %}" alt="Python logo">
                                <img style="width:5vw" src="{% static 'img/numpy.svg' %}" alt="Numpy logo">
                                <img style="width:5vw" src="{% static 'img/pandas.svg' %}" alt="Pandas logo">
                                <img style="width:5vw" src="{% static 'img/scikitlearn.svg' %}" alt="Scikitlearn logo">
                                <img style="width:5vw" src="{% static 'img/open_neural_network_exchange_logo.svg' %}" alt="Open Neural Network Exchange logo">
                                <img style="width:5vw" src="{% static 'img/django.svg' %}" alt="Django logo">
                                <img style="width:5vw" src="{% static 'img/bootstrap.svg' %}" alt="Bootstrap logo">
                            </div>
                            
                            <p class="card-text">
                                A restaurant web application demostration. Here I applied Natural Language Processing (NLP) to 
                                classify user reviews and get user satisfaction. This application use 
                                <a href="https://www.kaggle.com/datasets/gorororororo23/european-restaurant-reviews" target="_blank">European Restaurant Reviews dataset</a>.
                            </p>
        
                            <a href="{% url "restaurant:home" %}" target="_blank">Restaurant</a>
                        </div>
                        
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/titanic_survivor_app.png' %}" alt="Titanic project using Django and other tools">
                        
                        <div class="card-body">
                                
                            <div>                                
                                <img style="width:5vw" src="{% static 'img/python.svg' %}" alt="Python logo">
                                <img style="width:5vw" src="{% static 'img/numpy.svg' %}" alt="Numpy logo">
                                <img style="width:5vw" src="{% static 'img/pandas.svg' %}" alt="Pandas logo">
                                <img style="width:5vw" src="{% static 'img/scikitlearn.svg' %}" alt="Scikitlearn logo">
                                <img style="width:5vw" src="{% static 'img/django.svg' %}" alt="Django logo">
                                <img style="width:5vw" src="{% static 'img/bootstrap.svg' %}" alt="Bootstrap logo">
                            </div>
                            
                            <p class="card-text">
                                Web application that try to predict if you survive to Titanic sinking, using
                                Machine Learning algorithm over <a href="https://www.kaggle.com/datasets/vinicius150987/titanic3" target="_blank">Titanic Dataset</a>.
                            </p>
        
                            <a href="{% url "titanic:form" %}" target="_blank">Titanic</a>
                        </div>
                        
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/recommender_engine_app.jpg' %}" alt="Screenshoot of Movie Recommender application">
                        
                        <div class="card-body">
                                
                            <div>                                
                                <img style="width:5vw" src="{% static 'img/python.svg' %}" alt="Python logo">
                                <img style="width:5vw" src="{% static 'img/numpy.svg' %}" alt="Numpy logo">
                                <img style="width:5vw" src="{% static 'img/pandas.svg' %}" alt="Pandas logo">
                                <img style="width:5vw" src="{% static 'img/scikitlearn.svg' %}" alt="Scikitlearn logo">
                                <img style="width:5vw" src="{% static 'img/django.svg' %}" alt="Django logo">
                                <img style="width:5vw" src="{% static 'img/bootstrap.svg' %}" alt="Bootstrap logo">
                            </div>
                            
                            <p class="card-text">
                                Web application that recommend similar movies, using pairwise distance between them and 
                                <a href="https://datasets.imdbws.com/" target="_blank">Title Basics IMdb dataset</a>.
                            </p>
        
                            <a href="{% url "movie:search_form" %}" target="_blank">Movie</a>
                        </div>
                        
                    </div>
                </div>                

            </div>

            <div class="row">
                
                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/note_project.png' %}" alt="Note project using Django and other tools">
                        
                        <div class="card-body">
                                
                            <div>                                    
                                <img style="width:5vw" src="{% static 'img/postgresql.svg' %}" alt="PostgreSQL logo">
                                <img style="width:5vw" src="{% static 'img/python.svg' %}" alt="Python logo">
                                <img style="width:5vw" src="{% static 'img/django.svg' %}" alt="Django logo">
                                <img style="width:5vw" src="{% static 'img/bootstrap.svg' %}" alt="Bootstrap logo">
                            </div>
                            
                            <p class="card-text">
                                This application allows us manage notes, using web browser.
                            </p>
        
                            <a href="{% url "note:list" %}" target="_blank">Note</a>
                        </div>
                        
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card">
                        
                        <img class="card-img" src="{% static 'img/bazaar_project.jpg' %}" alt="Bazaar project using Django and other tools">
                        
                        <div class="card-body">
                                
                            <div>                                    
                                <img style="width:5vw" src="{% static 'img/postgresql.svg' %}" alt="PostgreSQL logo">
                                <img style="width:5vw" src="{% static 'img/python.svg' %}" alt="Python logo">
                                <img style="width:5vw" src="{% static 'img/django.svg' %}" alt="Django logo">
                                <img style="width:5vw" src="{% static 'img/bootstrap.svg' %}" alt="Bootstrap logo">
                            </div>
                            
                            <p class="card-text">
                                This application allows buy and sell things. It is a virtual bazar.
                            </p>
        
                            <a href="{% url "bazaar:home" %}" target="_blank">Bazaar</a>
                        </div>
                        
                    </div>
                </div>

            </div>            
            
        </section>

        <section class="text-center" id="code">
            
            <h2>Code</h2>
            
            <p>You can see the code of the projects on <a href="https://github.com/arielb0" target="_blank">Github</a></p>

        </section>

        <section class="text-center" id="contact_me">
            
            <h2>Contact</h2>

            <img class="img-fluid" src="{% static 'img/telegram.svg' %}" alt="Telegram">
            <a href="http://t.me/ascull" target="_blank">Telegram</a>
            
            
            <img class="img-fluid" src="{% static 'img/linkedin.svg' %}" alt="LinkedIn">
            <a href="http://www.linkedin.com/in/ariel-scull-b4a598183" target="_blank">LinkedIn</a>

        </section>

    </main>
{% endblock %}

templates/home_header.html
{% extends "header.html" %}

{% load i18n %}

{% block offcanvas_header %}
    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Scull Suite</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="{% translate "Close" %}"></button>
{% endblock  %}

{% block offcanvas_body %}
    <ul class="navbar-nav">
        <li>
            {% include "theme_button.html" %}
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#start">{% translate "Start" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#applications">{% translate "Applications" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#contact_me">{% translate "Contact" %}</a>
        </li>
    </ul>
{% endblock  %}

templates/navbar.html
<nav class="navbar navbar-expand-lg fixed-top bg-body-tertiary">
    <div class="container-fluid">
        {% block navbar_content %}{% endblock %}
    </div>
</nav>

templates/no_authenticated.html
{% extends "base.html" %}