feedback/urls.py
from django.urls import path
from .views import CreateSurvey, DetailSurvey, UpdateSurvey, DeleteSurvey, ListSurvey, SubmitSurvey
from .views import CreateQuestion, DetailQuestion, UpdateQuestion, DeleteQuestion, ListQuestion
from .views import CreateAnswer, DetailAnswer, UpdateAnswer, DeleteAnswer, ListAnswer
from .views import FaqView

app_name = 'feedback'

urlpatterns = [
    path('survey/create', CreateSurvey.as_view(), name = 'survey_create'),
    path('survey/<int:pk>/detail', DetailSurvey.as_view(), name = 'survey_detail'),
    path('survey/<int:pk>/update', UpdateSurvey.as_view(), name = 'survey_update'),
    path('survey/<int:pk>/delete', DeleteSurvey.as_view(), name = 'survey_delete'),
    path('', ListSurvey.as_view(), name = 'survey_list'),
    path('survey/<int:pk>/submit', SubmitSurvey.as_view(), name='survey_submit'),
    path('question/create', CreateQuestion.as_view(), name = 'question_create'),
    path('question/<int:pk>/detail', DetailQuestion.as_view(), name = 'question_detail'),
    path('question/<int:pk>/update', UpdateQuestion.as_view(), name = 'question_update'),
    path('question/<int:pk>/delete', DeleteQuestion.as_view(), name = 'question_delete'),
    path('question', ListQuestion.as_view(), name = 'question_list'),
    path('answer/create', CreateAnswer.as_view(), name = 'answer_create'),
    path('answer/<int:pk>/detail', DetailAnswer.as_view(), name = 'answer_detail'),
    path('answer/<int:pk>/update', UpdateAnswer.as_view(), name = 'answer_update'),
    path('answer/<int:pk>/delete', DeleteAnswer.as_view(), name = 'answer_delete'),
    path('answer', ListAnswer.as_view(), name = 'answer_list'),
    path('faq', FaqView.as_view(), name = 'faq')
]

note/urls.py
from django.urls import path
from note import views

app_name = "note"

urlpatterns = [
    path("create", views.CreateNote.as_view(), name = "create"),
    path("<int:pk>", views.ReadNote.as_view(), name = "read"),
    path("<int:pk>/update", views.UpdateNote.as_view(), name = "update"),
    path("<int:pk>/delete", views.DeleteNote.as_view(), name = "delete"),
    path("", views.ListNote.as_view(), name="list")
]

scull_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# for deploy uploaded files. Only for development
# environments
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),    
    path("note/", include("note.urls")),
    path("accounts/", include("accounts.urls")),
    path('bazaar/', include('bazaar.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('feedback/', include('feedback.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('image2text/', include('image2text.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Remember, only for debug mode! This code does not work on production environment..

feedback/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.utils.text import slugify

class Survey(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 128)
    description = models.TextField(verbose_name = _('Description'), max_length= 255)
    open = models.BooleanField(verbose_name = _('Open'))
    user = models.ForeignKey(verbose_name = _('User'), to = User, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.title}'

class Question(models.Model):
    survey = models.ForeignKey(verbose_name = _('Survey'), to = Survey, on_delete = models.CASCADE)
    text = models.CharField(verbose_name = _('Text'), max_length = 128)
    slug = models.SlugField()
    index = models.IntegerField(verbose_name= _('Index'), default=0)
    class FieldTypeChoices(models.TextChoices):
        SELECT = 'SL', _('Select')
        RADIO_SELECT = 'RS', _('Radio Select')
        CHECK_BOX = 'CB', _('Check Box')
        NUMBER_INPUT = 'NI', _('Number Input')
    field_type = models.CharField(verbose_name = _('Type'), max_length = 2, choices = FieldTypeChoices)
    min_value = models.IntegerField(verbose_name = _('Min value'), default=0)
    max_value = models.IntegerField(verbose_name = _('Max value'), default=255)

    def __str__(self):
        return f'{self.survey.title} - {self.text}'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.text)
        return super().save(*args, **kwargs)

class Answer(models.Model):
    question = models.ForeignKey(verbose_name = _('Question'), to = Question, on_delete = models.CASCADE)
    text = models.TextField(verbose_name = _('Text'))

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'{self.question}: {self.text}'

class Data(models.Model):
    question = models.ForeignKey(verbose_name = _('Question'), to = Question, on_delete = models.CASCADE)
    answer = models.IntegerField(verbose_name = _('Answer'))

    def __str__(self):
        return f'{self.question.survey}, {self.question}, {self.answer}'

feedback/forms.py
from django.forms import ModelForm
from .models import Survey, Question, Answer
from django.forms.widgets import TextInput, Textarea, Select, CheckboxInput, NumberInput
from django_recaptcha.fields import ReCaptchaField, ReCaptchaV3

class SurveyForm(ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    class Meta:
        model = Survey
        fields = ['title', 'description', 'open']
        widgets = {
            'title': TextInput(attrs = {'class': 'form-control'}),
            'description': Textarea(attrs = {'class': 'form-control'}),
            'open': CheckboxInput(attrs={'class': 'form-check-input'}),
            'captcha': TextInput()
        }

class QuestionForm(ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3)
    
    class Meta:
        model = Question
        fields = ['survey', 'text', 'index', 'field_type', 'min_value', 
                  'max_value']
        widgets = {
            'survey': Select(attrs = {'class': 'form-select'}),
            'text': TextInput(attrs = {'class': 'form-control'}),
            'index': NumberInput(attrs = {'class': 'form-control'}),
            'field_type': Select(attrs = {'class': 'form-control'}),
            'min_value': NumberInput(attrs = {'class': 'form-control'}),
            'max_value': NumberInput(attrs = {'class': 'form-control'}),
        }

class AnswerForm(ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    class Meta:
        model = Answer
        fields = ['question', 'text']
        widgets = {
            'question': Select(attrs = {'class': 'form-control'}),
            'text': TextInput(attrs = {'class': 'form-control'}),
        }

feedback/views.py
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, FormView, TemplateView
from .forms import SurveyForm, QuestionForm, AnswerForm
from .models import Survey, Question, Answer, Data
from django.urls import reverse_lazy
from django.http.response import HttpResponseRedirect
from .helpers import create_form, get_stats, get_charts
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class CreateSurvey(LoginRequiredMixin, CreateView):
    model = Survey
    form_class = SurveyForm
    success_url = reverse_lazy('feedback:survey_list')

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

class DetailSurvey(UserPassesTestMixin, DetailView):
    model = Survey

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stats'] = get_stats(self.get_object())
        context['charts'] = get_charts(self.get_object())
        
        return context
    
    def test_func(self):
        # A user can see survey statistics if is the survey owner or survey is open
        survey = self.get_object()
        return self.request.user.pk == survey.user.pk or survey.open

class UpdateSurvey(UserPassesTestMixin, UpdateView):
    model = Survey
    form_class = SurveyForm
    success_url = reverse_lazy('feedback:survey_list')

    def test_func(self):
        return self.request.user == self.get_object().user

class DeleteSurvey(UserPassesTestMixin, DeleteView):
    model = Survey
    success_url = reverse_lazy('feedback:survey_list')

    def test_func(self):
        return self.request.user == self.get_object().user

class ListSurvey(ListView):
    model = Survey

class SubmitSurvey(FormView):
    template_name = 'feedback/survey_submit.html'
    success_url = reverse_lazy('feedback:survey_list')

    def get_form_class(self):
        return create_form(Survey.objects.get(pk=self.kwargs['pk']))
    
    def form_valid(self, form):

        for key, value in form.cleaned_data.items():
            if key != 'captcha':
                if type(value) == list:
                    for single_value in value: # Useful for fields that allow several values (Checkbox)
                        data = Data.objects.create(question= Question.objects.get(slug=key), answer=single_value)
                        data.save()
                else:
                    data = Data.objects.create(question= Question.objects.get(slug=key), answer=value)
                    data.save()

        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Survey.objects.get(pk=self.kwargs['pk']).title
        return context

class CreateQuestion(UserPassesTestMixin, CreateView):
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy('feedback:question_list')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['survey'].queryset = Survey.objects.filter(user=self.request.user)
        return form

    def test_func(self):        
        if 'data' in self.get_form_kwargs().keys():
            survey_pk = self.get_form_kwargs()['data']['survey']            
            
            try:
                survey = Survey.objects.get(pk=survey_pk)
                return survey.user == self.request.user
            except:
                return False
        
        return True
            
class DetailQuestion(DetailView): # TODO: This view has no purpose.
    model = Question

class UpdateQuestion(UserPassesTestMixin, UpdateView):
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy('feedback:question_list')

    def test_func(self):
        return self.request.user == self.get_object().survey.user

class DeleteQuestion(UserPassesTestMixin, DeleteView):
    model = Question
    success_url = reverse_lazy('feedback:question_list')

    def test_func(self):
        return self.request.user == self.get_object().survey.user

class ListQuestion(LoginRequiredMixin, ListView):
    model = Question

    def get_queryset(self):
        return Question.objects.filter(survey__user=self.request.user)

class CreateAnswer(UserPassesTestMixin, CreateView):
    model = Answer
    form_class = AnswerForm
    success_url = reverse_lazy('feedback:answer_list')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['question'].queryset = Question.objects.filter(survey__user=self.request.user)
        return form
    
    def test_func(self):
                
        if 'data' in self.get_form_kwargs().keys():
            question_pk = self.get_form_kwargs()['data']['question']
            
            try:
                question = Question.objects.get(pk=question_pk)
                return question.survey.user == self.request.user
            except:
                return False
        
        return True

class DetailAnswer(DetailView): # TODO: This view does not have purpose. Delete it
    model = Answer

class UpdateAnswer(UserPassesTestMixin, UpdateView):
    model = Answer
    form_class = AnswerForm
    success_url = reverse_lazy('feedback:answer_list')

    def test_func(self):
        return self.request.user == self.get_object().question.survey.user

class DeleteAnswer(UserPassesTestMixin, DeleteView):
    model = Answer
    success_url = reverse_lazy('feedback:answer_list')

    def test_func(self):
        return self.request.user == self.get_object().question.survey.user

class ListAnswer(LoginRequiredMixin, ListView):
    model = Answer
    success_url = reverse_lazy('feedback:answer_list')

    def get_queryset(self):
        return Answer.objects.filter(question__survey__user=self.request.user)
    
class FaqView(TemplateView):
    template_name = 'feedback/faq.html'

feedback/templates/feedback/answer_confirm_delete.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% translate "Answer Delete Confirmation" %}{% endblock %}

{% block main %}
<h1>{% translate "Answer Delete Confirmation" %}</h1>
<p>{% translate "This process can be undone. Are you sure?" %}</p>
<a class="btn btn-primary" href="feedback:answer_list">{% translate "No" %}</a>
<form action="" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate "Yes" %}">
</form>
{% endblock %}

feedback/templates/feedback/answer_detail.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{{ object.question.text }} | {% translate "Answer details" %} {% endblock %}

{% block main %}
    <h1>{% translate "Answer details" %}</h1>
    <ul>
        <li>{% translate "Survey:" %} {{ object.question.survey }}</li>
        <li>{% translate "Question:" %} {{ object.question.text }}</li>
        <li>{% translate "Answer:" %} {{ object.text }}</li>
    </ul>
    <div>
        <a class="btn btn-primary" href="{% url "feedback:answer_update" pk=object.pk %}">{% translate "Update" %}</a>
        <a class="btn btn-danger" href="{% url "feedback:answer_delete" pk=object.pk %}">{% translate "Delete" %}</a>
    </div>
{% endblock %}

feedback/templates/feedback/answer_form.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% include "action_label.html" %}{% translate " an Answer" %}{% endblock %}

{% block main %}
    <h1>{% include "action_label.html" %} {% translate " an Answer" %}</h1>
    <form action="" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">{% include "action_label.html" %}</button>
    </form>
{% endblock %}

feedback/templates/feedback/answer_list.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% translate "Answers" %}{% endblock %}

{% block main %}
    <h1>{% translate "Answers" %}</h1>
    <a class="btn btn-primary" href="{% url "feedback:answer_create" %}" >{% translate "Create Answer" %}</a>
    {% if object_list %}
        <ul>
            {% for object in object_list %}
                <li>
                    <a href="">{{ object }}</a>
                    <a class="btn btn-primary" href="{% url "feedback:answer_update" pk=object.pk %}">{% translate "Update" %}</a>
                    <a class="btn btn-danger" href="{% url "feedback:answer_delete" pk=object.pk %}">{% translate "Delete" %}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% translate "There are not answers available." %}</p>
    {% endif %}
{% endblock  %}

feedback/templates/feedback/base.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block page_icon %}{% static "chattext.svg" %}{% endblock %}

{% block title %}{% block title_prefix %}{% endblock title_prefix %} | Feedback {% endblock title %}

{% block header %}
    {% url "feedback:survey_list" as header_url %}
    {% include "feedback/header.html" with url=header_url icon='chat-text' title='Feedback' show_user_menu=True %}
{% endblock %}

{% block footer %}
    <div class="navbar navbar-expand bg-body-tertiary">
        <div class="container-fluid justify-content-center">
            <span class="navbar-text">Feedback</span>
        </div>
    </div>
{% endblock %}

feedback/templates/feedback/header.html
{% extends "header.html" %}

{% load i18n %}

{% block offcanvas_header %}
    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Feedback</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="{% translate "Close" %}"></button>
{% endblock %}

{% block offcanvas_body %}
    <ul class="navbar-nav">
        {% include "theme_button.html" %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "feedback:survey_list" %}">{% translate "Surveys" %}</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "feedback:question_list" %}">{% translate "Questions" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "feedback:answer_list" %}">{% translate "Answers" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "read_user" pk=user.pk %}">{% translate "User" %}</a>
            </li>
            <li class="nav-item">
                <form action="{% url "logout" %}?next={{ request.path }}" method="post">
                    {% csrf_token %}
                    <input class="nav-link" type="submit" value="{% translate "Logout" %}">
                </form>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "login" %}?next={{ request.path }}">{% translate "Login" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "register" %}">{% translate "Register" %}</a>
            </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "feedback:faq" %}">{% translate "Frequently Asked Questions" %}</a>
        </li>
        
    </ul>
{% endblock %}

feedback/templates/feedback/question_confirm_delete.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% translate "Question Delete Confirmation" %}{% endblock %}

{% block main %}
<h1>{% translate "Question Delete Confirmation" %}</h1>
<p>{% translate "This process can be undone. Are you sure?" %}</p>
<a class="btn btn-primary" href="{% url "feedback:question_list" %}">{% translate "No" %}</a>
<form action="" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate "Yes" %}">
</form>
{% endblock %}

feedback/templates/feedback/question_detail.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{{ object.text }}{% endblock %}

{% block main %}
    <h1>{% translate "Question details" %}</h1>
    <ul>
        <li>{% translate "Survey:" %} <a href="{% url "feedback:survey_detail" pk=object.survey.pk %}">{{ object.survey.title }}</a></li>
        <li>{% translate "Text:" %} {{ object.text }}</li>
        <li>{% translate "Field type:" %} {{ object.field_type }}</li>
        <li>{% translate "Required:" %} {{ object.required }}</li>
        <li>{% translate "Min Value:" %} {{ object.min_value }}</li>
        <li>{% translate "Max Value:" %} {{ object.max_value }}</li>
    </ul>
    <a class="btn btn-primary" href="{% url "feedback:question_update" pk=object.pk %}">{% translate "Update" %}</a>
    <a class="btn btn-danger" href="{% url "feedback:question_delete" pk=object.pk %}">{% translate "Delete" %}</a>
{% endblock %}

feedback/templates/feedback/question_form.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% include "action_label.html" %} {% translate "a Question" %}{% endblock %}

{% block main %}
    <h1>{% include "action_label.html" %} {% translate "a Question" %}</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">{% include "action_label.html" %}</button>
    </form>
{% endblock %}

feedback/templates/feedback/question_list.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% translate "Questions" %}{% endblock %}

{% block main %}
    <h1>{% translate "Questions" %}</h1>
    <a class="btn btn-primary" href="{% url "feedback:question_create" %}" >{% translate "Create Question" %}</a>
    {% if object_list %}
        <ul>
            {% for object in object_list %}
                <li>
                    <a href="">{{ object }}</a>
                    <a class="btn btn-primary" href="{% url "feedback:question_update" pk=object.pk %}">{% translate "Update" %}</a>
                    <a class="btn btn-danger" href="{% url "feedback:question_delete" pk=object.pk %}">{% translate "Delete" %}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% translate "There are not questions available." %}</p>
    {% endif %}
{% endblock  %}

feedback/templates/feedback/survey_confirm_delete.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% translate "Survey Delete Confirmation" %}{% endblock %}

{% block main %}
<h1>{% translate "Survey delete confirmation" %}</h1>
<p>{% translate "This process can be undone. Are you sure?" %}</p>
<a class="btn btn-primary" href="feedback:survey_list">{% translate "No" %}</a>
<form action="" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate "Yes" %}">
</form>
{% endblock %}

feedback/templates/feedback/survey_form.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block title_prefix %}{% include "action_label.html" %} {% translate "a Survey" %}{% endblock  %}

{% block main %}
    <h1>{% include "action_label.html" %} {% translate "a Survey" %}</h1>
    <form action="" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">{% include "action_label.html" %}</button>
    </form>
{% endblock %}

feedback/templates/feedback/survey_list.html
{% extends "feedback/base.html" %}

{% load i18n %}

{% block page_description %}{% translate "Free online surveys. Make data driven decisions for your business" %}{% endblock %}

{% block title_prefix %}{% translate "Surveys" %}{% endblock %}

{% block main %}
    <h1>{% translate "Surveys" %}</h1>
    <a class="btn btn-primary" href="{% url "feedback:survey_create" %}" >{% translate "Create Survey" %}</a>
    {% if object_list %}
        <ul>
            {% for object in object_list %}
                <li>
                    <a href="{% url "feedback:survey_submit" pk=object.pk %}">{{ object.title }}</a>
                    {% if object.open or object.user == user%}
                        <a class="btn btn-secondary" href="{% url "feedback:survey_detail" pk=object.pk %}">{% translate "Statistics" %}</a>
                    {% endif %}
                    {% if object.user == user %}
                        <a class="btn btn-primary" href="{% url "feedback:survey_update" pk=object.pk %}">{% translate "Update" %}</a>
                        <a class="btn btn-danger" href="{% url "feedback:survey_delete" pk=object.pk %}">{% translate "Delete" %}</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% translate "There are not surveys available." %}</p>
    {% endif %}
{% endblock  %}